stages:
  - build
  - deploy

variables:
  IMAGE_NAME: react-app

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - apk add --no-cache bash
    - cd my-app
    - docker build --no-cache -t $IMAGE_NAME .

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd my-app
    - docker rm -f node-app || true
    - docker run -d -p 80:80 --name node-app $IMAGE_NAME
